stages:
  - build
  - deploy

image: bellsoft/liberica-openjdk-alpine:8u252-9

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  HEROKU_API_KEY: "e74f17e1-acb9-425f-bd80-09ed868a5ad2"

cache:
  paths:
    - ./.m2/repository

Build:
  stage: build
  when: on_success
  before_script:
    - chmod +x mvnw
  script:
    - ./mvnw $MAVEN_OPTS install

Heroku Deploy:
  stage: deploy
  when: manual
  image: ruby:latest
  cache: {}
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=softserve2020romeo --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://softserve2020romeo.herokuapp.com/
  only:
    - dev